delete from j_agent;
delete from j_merchant;
delete from j_sub;
delete from j_maccount;
delete from j_balance;
delete from j_log;
delete from j_card;
delete from j_exchange;
delete from j_money;
delete from j_vpa_job;
delete from j_vpa_adjust;
delete from sys_log_error;
delete from sys_log_login;
delete from sys_log_operation;
delete from j_allocate;
delete from j_deposit;
delete from j_withdraw;
delete from j_auth;
delete from j_packet;
delete from j_channel_log;
delete from j_va;
delete from j_stat;
delete from j_batch;

delete from sys_dept where name not in ('大吉');
delete from sys_user where username not in ('dj', 'admin');
delete from sys_role where name not in ('大吉管理员');
